# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.EbpfForWindows
PackageVersion: 0.6.0
PackageName: EbpfForWindows
PackageLocale: en-US
Publisher: Microsoft Corporation
License: MIT License
ShortDescription: eBPF platform for Windows
ManifestType: defaultLocale
ManifestVersion: 1.4.0
